# 1. Write a Python Program to Add Two Matrices?

In [1]:
import numpy as np
mat1 = np.array([[1,2,3],
        [4,5,6],
        [7,8,9]])

mat2 = np.array([[10,11,12],
                [13,14,15],
                [16,17,18]])

summation = np.add(mat1, mat2)
print(f'The Sum of two matrix \n\n{mat1} and \n\n{mat2} is \n\n{summation}')

The Sum of two matrix 

[[1 2 3]
 [4 5 6]
 [7 8 9]] and 

[[10 11 12]
 [13 14 15]
 [16 17 18]] is 

[[11 13 15]
 [17 19 21]
 [23 25 27]]


# 2. Write a Python Program to Multiply Two Matrices?

In [2]:
mat1 = np.array([[1,2,3],
        [4,5,6],
        [7,8,9]])

mat2 = np.array([[10,11,12],
                [13,14,15],
                [16,17,18]])

Multiplication = np.dot(mat1, mat2)
print(f'The multiplication of two matrix \n\n{mat1} and \n\n{mat2} is \n\n{Multiplication}')

The multiplication of two matrix 

[[1 2 3]
 [4 5 6]
 [7 8 9]] and 

[[10 11 12]
 [13 14 15]
 [16 17 18]] is 

[[ 84  90  96]
 [201 216 231]
 [318 342 366]]


# 3. Write a Python Program to Transpose a Matrix?

In [3]:
No = 4
def tranpose(A,B):
    for i in range(No):
        for j in range(No):
            B[i][j] = A[j][i]
            
A = [[1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]]

B = A[:][:]

tranpose(A,B)
print('Result matrix is')
for i in range(No):
    for j in range(No):
        print(B[i][j],   " ", end = '')
    print()

Result matrix is
1  5  9  13  
5  6  10  14  
9  10  11  15  
13  14  15  16  


# 4. Write a Python Program to Sort Words in Alphabetic Order?

In [4]:
string= input('Enter a string:')

word = string.split()
word.sort()
for i in word:
    print(i)

Enter a string:towards the journey of data scientist.
data
journey
of
scientist.
the
towards


# 5. Write a Python Program to Remove Punctuation From a String?

In [5]:
Punctuation = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

string = input('enter a string with punctuation: ')

removed = ""
for i in string:
    if i not in Punctuation:
        removed = removed + i
print(removed)

enter a string with punctuation: let's check #@#$^@#$@#^^ * " is working
lets check    is working
